### ISSUE TITLE
plugin-review needs power-assert when it runs

### ISSUE THREAD

**Issue by kn1cht** [orangain/textlint-plugin-review#17]
## Problem
I installed textlint-plugin-review in my Re:VIEW project and ran textlint.
log:
```bash
$ npx textlint test.re  
✖ Error
Cannot find module 'power-assert'

✖ Stack trace
Error: Cannot find module 'power-assert'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/.../.../node_modules/textlint-plugin-review/lib/review-to-ast.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

I reviewed `lib/review-to-ast.js` and confirmed it certainly requires power-assert.

```js
var _powerAssert = require('power-assert');

var _powerAssert2 = _interopRequireDefault(_powerAssert);
```

However, native assert instead of power-assert seems to be used in the source JS file.
Is this an issue due to babel?

https://github.com/orangain/textlint-plugin-review/blob/2a1fe0b5786433a30ed5d82c7c30b0b6bea11680/src/review-to-ast.js#L2-L4

**Comment by orangain** [comment]
@kn1cht Thank you for reporting the issue! I've just fixed and published a new version of [textlint-plugin-review](https://www.npmjs.com/package/textlint-plugin-review). Please try to upgrade the plugin to v0.4.1.

The cause of this issue was that power-assert was enabled even when the npm module is published. I've fixed not to use power-assert on `npm run build`  https://github.com/orangain/textlint-plugin-review/commit/4cf8932d476e4ce89c1828c4d84dcd14ecc48c36.

**Comment by kn1cht** [comment]
@orangain I confirmed v0.4.1 works without power-assert.
ご対応ありがとうございます 😊
